spring.application.name=ClubSync

spring.datasource.url=jdbc:mysql://localhost:3306/club-sync?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/clubsync

application.security.jwt.secret-key=79ab0b03323f83d355730cc12e5bf9240a7dd102390c00c4c828ed494e7d97af
application.security.jwt.access-token-expiration=86400000
application.security.jwt.refresh-token-expiration=604800000